name: Deploy
concurrency: deploy
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  deploy:
    if: github.repository == 'trnila/assistant'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: 'curl -X POST --fail -s -H"Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" https://trnila.eu/hooks/assistant'
